# This file is machine-generated - editing it directly is not advised

julia_version = "1.9.2"
manifest_format = "2.0"
project_hash = "8f13d9ea6c8bf0f95c6f3f4d469c06981a4f0e58"

[[deps.Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[deps.Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[deps.Random]]
deps = ["SHA", "Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[deps.SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"
version = "0.7.0"

[[deps.Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[deps.ToolipsSVG]]
deps = ["ToolipsServables"]
git-tree-sha1 = "eb4513cab88ebed20396834bcd634e97cba3655d"
uuid = "8ae86ec9-919d-4ece-9a6d-09b7d28dae11"
version = "0.2.0"

[[deps.ToolipsServables]]
deps = ["Base64", "Markdown"]
git-tree-sha1 = "e02af2fc4dbd076d3ec905fab802d51884ab84af"
uuid = "bf3a9e68-ca66-4981-8178-9d71c4f8abaa"
version = "0.1.3"
